import Head from "next/head"
import { useCallback, useEffect, useState } from "react"
import { Box } from "@mui/material"
import { Header } from "@/components/header"
import { Scripture } from "@/components/scripture"
import { TargetUserList } from "@/components/targetUserList"
import { Loading } from "@/components/loading"

export default function Home() {
  const [loading, setLoading] = useState(true)
  const [allUsers, setAllUsers] = useState<TargetUser[]>([])

  // Fetch user data from the API
  const fetchTargetUser = useCallback(async (): Promise<TargetUser[]> => {
    try {
      const response = await fetch("/api/getTargetReminder")

      if (!response.ok) {
        throw new Error(`HTTP error! status: ${response.status}`)
      }

      const data = await response.json()

      // Ensure data is returned as an array of objects
      return data["ids"] as TargetUser[]
    } catch (err) {
      console.error("Error:", err)
      window.alert("Something went wrong, please contact the developer")

      // Return an empty array to avoid potential undefined issues
      return []
    }
  }, [])

  // Fetch the user data when the component mounts
  useEffect(() => {
    const fetchData = async () => {
      const fetchStart = Date.now() // Record the start time
      const usersData = await fetchTargetUser()
      setAllUsers(usersData) // Set the fetched data into state

      // Calculate elapsed time and wait if it's less than 5 seconds
      const elapsedTime = Date.now() - fetchStart
      const remainingTime = Math.max(5000 - elapsedTime, 0) // Calculate remaining time

      setTimeout(() => {
        setLoading(false) // Hide loading after the remaining time
      }, remainingTime)
    }

    fetchData()
  }, [fetchTargetUser])

  if (loading) return <Loading />

  return (
    <Box
      height="100%"
      display="flex"
      justifyContent="center"
      alignItems="center"
      width="100%"
    >
      <Head>
        <title>Penatalayan Reminder</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box
        width="100%"
        display="flex"
        flexDirection="column"
        gap={5}
        maxWidth={430}
        bgcolor="white"
        padding={4}
        height="100%"
      >
        <Header />
        <Scripture />
        <TargetUserList userList={allUsers} />
      </Box>
    </Box>
  )
}
