import Head from "next/head"
import { useCallback, useState } from "react"

export default function Home() {
  const [loading, setLoading] = useState(false)
  const triggerReminder = useCallback(async () => {
   try {
    setLoading(true)
    const response = await fetch("/api/remindPelayanan", {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
      },
      body: JSON.stringify({
        //  "lineUserId": "C0d78a713f5ea0a0dbf57b4d266032fa8"
         "lineUserId": "U0d024765bddf5730d824a687ecd4d474"
      })
    })

    if(!response.ok) {
      throw new Error(`HTTP error! status: ${response.status}`)
    }

    await response.json()
    window.alert("reminder sent successfully")
   } catch (error) {
    console.error("Error: ", error)
    window.alert("Something went wrong, please contact developer")
   } finally {
    setLoading(false)
   }
  }, [])

  return (
    <div>
      <Head>
        <title>Penatalayan reminder</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <div style={{
          paddingTop: "70px",
          minWidth:"100%",
          display: "flex",
          alignItems: "center",
          justifyContent:"center",
          textAlign:"center"
        }}>
          <button
            className="triggerButton"
            onClick={triggerReminder}
            style={{cursor:"pointer"}}
          >
            <h2>
              {!loading ? "Trigger" : "Loading..."}
            </h2>
            <p>
            {!loading ? "Trigger reminder template manually" : "Sending reminder...."}
            </p>
          </button>
        </div>
    </div>
  )
}
