import type { NextApiRequest, NextApiResponse } from "next"
import { GoogleSpreadsheet } from "google-spreadsheet"
import { JWT } from "google-auth-library"

interface ResponseData {
  message: string
}

export interface GroupInfo {
  "Group Id": string
  "Group Name": string
  "Picture URL": string
}

export interface UserInfo {
  "Display Name": string
  "Profile Picture URL": string
  "Status Message": string
  "User ID": string
}

type RequestBody = GroupInfo | UserInfo

const googleSheetId = "1_wXgkAdoLIPdZjXknpuI6uO5jrA2hf0qNoeXK_qd9lU"

const sheetInfo = {
  user: "User Info",
  group: "Group Info"
}

export default async function handler(
  req: NextApiRequest,
  res: NextApiResponse<ResponseData>,
) {
  try {
    if (req.method !== "POST") return res.status(405).json({ message: "Only POST method allowed" })
    const userData = req.body as RequestBody

    // log user data to sheet
    const serviceAccountAuth = new JWT({
      // env var values here are copied from service account credentials generated by google
      // see "Authentication" section in docs for more info
      email: process.env.GOOGLE_SERVICE_EMAIL,
      key: process.env.GOOGLE_PRIVATE_KEY,
      scopes: [
        "https://www.googleapis.com/auth/spreadsheets",
      ],
    })

    // setup google sheet
    const doc = new GoogleSpreadsheet(googleSheetId, serviceAccountAuth)
    await doc.loadInfo()

    // get user and group sheets
    const userSheet = doc.sheetsByTitle[sheetInfo.user]
    const groupSheet = doc.sheetsByTitle[sheetInfo.group]

    // check user or group
    if ("User ID" in userData) {
      const userRows = await userSheet.getRows()
      const matchingRow = userRows.findIndex((item) => {
        const row = item.toObject()
        if (row["User ID"] === userData["User ID"]) return true
        return false
      })

      if (matchingRow === -1) {
        // append value to user sheet
        await userSheet.addRow(userData as unknown as Record<string, string>)
      }
    } else {
      const groupRows = await groupSheet.getRows()
      const matchingRow = groupRows.findIndex((item) => {
        const row = item.toObject()
        if (row["Group Id"] === userData["Group Id"]) return true
        return false
      })

      if (matchingRow === -1) {
        // append value to group sheet
        await groupSheet.addRow(userData as unknown as Record<string, string>)
      }
    }

    res.status(200).json({ message: "User Logged!" })
  } catch (err) {
    console.error(err)
    res.status(500).json({ message: "Something went wrong" })
  }
}
